version: 2

project_name: socialbu

before:
  hooks:
    - go mod verify
    - go test ./...

builds:
  - id: socialbu
    main: ./main.go
    binary: socialbu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}

archives:
  - id: default
    ids:
      - socialbu
    formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: git

release:
  draft: false
  prerelease: auto
