# This file was generated by GoReleaser. DO NOT EDIT.
cask "socialbu" do
  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "0d149adcaba70353172ddbf0a27187936d658b4e70d04e639325dee0fdbae0e6"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8de3e96fb3a03ad5cf41f0923360747bfca4623537e109e4e3e11515f6a2b779"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "96b8c5c858e3cc9cce427c5cb1be382ae40715ef72c500bd1b19ddfc717a0c25"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "449da1646bc5b50463e67d9da186d6c34c602a396f7f04b313eddd6aafdd9dec"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "socialbu"
  desc "SocialBu CLI for accounts, posts, analytics, and more."
  homepage "https://socialbu.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "socialbu"

  # No zap stanza required
end
