# This file was generated by GoReleaser. DO NOT EDIT.
cask "socialbu" do
  version "0.1.10"

  on_macos do
    on_arm do
      sha256 "01a3c03219558af558b3cb99454e25ae83a94ddf8fdd637b8ad9b67aa22cee19"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e59f1bd146602e959f66e268f5c0327bbacd591b6bc5858630bb2c4cb6097171"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8700a57c29f8b7d0d8e70bf8df7c7de7c3ef64ff3e400f96204bbea38cd0e504"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9589e5982f4bc80ec73fbcda6c28c184b5cfbdbe6d92222430a97d62676132dd"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "socialbu"
  desc "SocialBu CLI for accounts, posts, analytics, and more."
  homepage "https://socialbu.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "socialbu"

  # No zap stanza required
end
