# This file was generated by GoReleaser. DO NOT EDIT.
cask "socialbu" do
  version "0.1.9"

  on_macos do
    on_arm do
      sha256 "4e0e157bf0eb6df47ccfc6b9a50cfd18118a20b5f417d394acbe2571df011b0d"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e4d8d79bc0888844d983975270daecdb54be00e4426b2a98cbe48dbecceaa6c9"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e3a4b801e4a9485f9137bc0b2bbae7a10e196fd6340c9e8000ea42b370b882a3"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "965dff23c10432b252b2eee4237ab17198a23c71f00a5dd8a246eb5abe20cd97"
      url "https://github.com/socialbu/socialbu-cli/releases/download/v#{version}/socialbu_#{version}_linux_amd64.tar.gz"
    end
  end

  name "socialbu"
  desc "SocialBu CLI for accounts, posts, analytics, and more."
  homepage "https://socialbu.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "socialbu"

  # No zap stanza required
end
